### ISSUE TITLE
Decide networking technology

### ISSUE THREAD

**Issue by BrendanOswego** [CSC480-18S/Blue-Team#1]

**Comment by William-Cook** [comment]
Pretty sure we've had this all worked out since early in the week, but if someone else could confirm before we close it please

**Comment by BrendanOswego** [comment]
To close an issue QA must be able to verify that it has been completed, if there is a document that states the network technologies please link it in the issue

**Comment by William-Cook** [comment]
Also, decided and tested. Can someone from Blue Team link documentation for closure?

**Comment by tealyn** [comment]
Here are notes from the meeting that we finalized all tech choices.

https://docs.google.com/document/d/1YrqAMMs5EktJ8FO4Wd2_7tGjghdfp-YbvzOSXPDAvxI/edit?usp=drivesdk

**Comment by BrendanOswego** [comment]
Thank you for the documentation, this is enough to close the issue.
