### ISSUE TITLE
Timer Thread not being closed properly- Memory Leak

### ISSUE THREAD

**Issue by andrewld3** [CSC480-18S/Blue-Team#177]
![sttimerthread](https://user-images.githubusercontent.com/25461105/39031675-a82fcfca-4437-11e8-86c1-4b164d6d599e.PNG)

See stack trace screenshot above.

**Comment by bohdan91** [comment]
Timer Thread is not being closed because you force close the application. It gives memory leak warning when you are closing, so I guess no memory will leak if it's being closed next second.
However, I redone timers to make it cleaner and using ShutDownHook closing timer when JVM closes.

**Comment by andrewld3** [comment]
I believe that your fix has created another issue. I cannot close the app on my laptop. I have to force kill 4 threads in order to close the app.
