### ISSUE TITLE
Game Logger is displaying Gibberish

### ISSUE THREAD

**Issue by andrewld3** [CSC480-18S/Blue-Team#179]
Bohdan, I know you are aware the issue. Just putting it on GitHub to track it.

For others: Game Log is pulling getSession().getLogger() and converting to String and displaying. GetLogger() returns an Object.

**Comment by bohdan91** [comment]
Session.getLogger I didn't do. It is leftover from initial logger that Rick made. I created very simple one, to call it use Log.getLogger().logException(e);

**Comment by bohdan91** [comment]
Someone was trying to print object, that's why it was displaying gibberish
printGameLog(Session.getSession().getLogger().toString());

**Comment by gcampbe3** [comment]
Displays proper values
