### ISSUE TITLE
generateQRCodeImage broken

### ISSUE THREAD

**Issue by andrewld3** [CSC480-18S/Blue-Team#180]
![qrproblem](https://user-images.githubusercontent.com/25461105/39032171-5b90321a-443a-11e8-9d2c-b86abbd425e9.PNG)

I had to comment this line out in order to get boards to load. 
When uncommented, I get IP  address repeated on console output and no jFrames will load.

**Comment by bohdan91** [comment]
I think it works on target and works on mine, so idk, we'll take a look on Friday if don't forget

**Comment by richardjamesw** [comment]
Closing - this works fine. User needs to verify the dependencies are included in their .war file build.
If the imports are not included there will be NoClassDefFoundError and the app will crash, causing the server to continuously restart.
