### ISSUE TITLE
Get test running of network implementation

### ISSUE THREAD

**Issue by BrendanOswego** [CSC480-18S/Blue-Team#2]

**Comment by William-Cook** [comment]
This was finished early last week.

**Comment by BrendanOswego** [comment]
Please do not close issues that are sprint tasks, issues with the type Sprint Tasks must be closed by QA based on information either in the repository, or that can be linked to outside information.

**Comment by William-Cook** [comment]
My understanding was this was successfully demoed. Can someone else on Blue Engine provide documentation to prove this so we can get it closed?

**Comment by tealyn** [comment]
https://docs.google.com/document/d/1ta4wZlX9wgdKgb670hxsNQqFmE5hDaPRebcKo45JwHU/edit?usp=sharing

Here is a link to our activity log. Is this enough documentation to close this issue?

**Comment by BrendanOswego** [comment]
@tealyn this should be fine because of the demo and the documentation follow, thank you for the documentation.
