### ISSUE TITLE
Selecting the Value of a Blank Tile Removes that Value from List of Possible Values

### ISSUE THREAD

**Issue by gcampbe3** [CSC480-18S/Blue-Team#207]
When the user selects what letter to use a blank tile as they are prompted with a screen full of all letters. Upon selecting one of these letters it is removed from the selection screen. Instead the user is greeted with a blank square outline for where the tile used to be located. This makes it so a blank tile can only be used as a certain letter once in the entirety of a game.

**Comment by richardjamesw** [comment]
Fixed with #227 .

**Comment by BrendanOswego** [comment]
login script only allows for one blank tile, this seems to fix the issue.
