### ISSUE TITLE
Played "Law", Kiosk changed to "La", Mobile changed to "Laa"

### ISSUE THREAD

**Issue by andrewld3** [CSC480-18S/Blue-Team#217]
I'm not even sure how to classify this bug. I played law and it was represented three different ways. No AI running at the time. 
![bug1](https://user-images.githubusercontent.com/25461105/39128018-abc61bfe-46d4-11e8-94ff-4c40c1d4f4a2.PNG)
![bug2](https://user-images.githubusercontent.com/25461105/39128019-abd6e95c-46d4-11e8-920d-2e886309202d.PNG)

**Comment by gcampbe3** [comment]
I just tried the exact same move on my machine and it worked, and I have never seen this before I am willing to bet that there is something wrong on your end as per usual

**Comment by gcampbe3** [comment]
![screenshot from 2018-04-23 13-03-07](https://user-images.githubusercontent.com/25461539/39159947-8f337b00-4736-11e8-9a18-87a730d226a9.png)
