### ISSUE TITLE
Mobile GUI Exchange Issue Causes Tile Carryover

### ISSUE THREAD

**Issue by gcampbe3** [CSC480-18S/Blue-Team#221]
When you exchange tiles, if you click on the board immediately after exchanging tiles, the last tile clicked is placed on the board. When the user clicks quit the it is counted amongst user placed tiles. Bohdan's hand check stops the word from being played but it is still placed on the board.

**Comment by BrendanOswego** [comment]
Looked at implementation and seems to be fixed.
